BankExpiry: 24-DEC-2024
BankSymbol: BANKNIFTY
EntryType: AUTO
Entry_Date: '2024-11-23'
Expiry: 26-DEC-2024
ICT: 40
IFT: 50
Past_M2M: 15423
Symbol: NIFTY
Update_EOD: 0
enter_strategy: M
enter_today: 0
interval: 60
live: 0
lot_size: 25
lots: 1
nfo_sym_path: NFO_symbols.txt
nse_sym_path: NSE_symbols.txt
num_adjustments: 0
percent_of_max_profit: 400
positions_data: csv
stop_loss: -5000000
target_profit: 5000000
